### PR TITLE
Update LSE-63.tex

### PR DESCRIPTION
**Pull request by timj**
@tonytyson This is a reimplementation of #2 but now part of the repository itself to allow me to make edits.

### CODE REVIEW

**Comment by timj** [comment]
I've fixed some spelling mistakes and add new and old text signifiers so that it's easier to work out what has changed. Github diffs aren't great for large paragraphs with no line breaks. @tonytyson do you want me to submit this to CCB to get it baselined quickly? I think the only issue would be if someone decides that LSE-63 is fundamentally wrong and requires a rewrite.

**Comment by tonytyson** [comment]
Yes, go ahead. Thanks.

**Comment by tonytyson** [comment]
Thanks. Go ahead.

**Comment by timj** [comment]
Submitted as [LCR-943](https://project.lsst.org/groups/ccb/node/1693).

**Comment by timj** [comment]
I've merged this into the LCR-943 ticket branch where we can track updates driven by feedback from the LCR.

**Pull request merged**
